services:
- type: web
  name: application-web
  env: java
  buildCommand: mvn clean package -DskipTests
  startCommand: java -jar target/application-web-0.0.1-SNAPSHOT.jar
  plan: free
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SPRING_DATASOURCE_URL
      value: jdbc:h2:file:/var/data/GestionTache
    - key: SPRING_DATASOURCE_USERNAME
      value: sa
    - key: SPRING_DATASOURCE_PASSWORD
      value: password
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - key: SPRING_H2_CONSOLE_ENABLED
      value: true
    - key: SPRING_H2_CONSOLE_PATH
      value: /h2-console
  disk:
    name: data
    mountPath: /var/data
    sizeGB: 1